<?php
$odeme = isset($odeme) ? $odeme: new Odeme($db);
$odeme->o_code = $item2;
$odeme->select();
$ayar->ayar_1 = $odeme->o_banka;
$banka = $ayar->id();
$siparis->sp_code = $item2;
$siparis->select();
$icerik = '<div style="background: #edf2f9; height: 100%;"><br><br><center><table cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" width="100%" style="max-width:600px;padding: 10px;" align="center">';
$icerik .= '<tr><th width="120"><img src="'.ns_filter('siteurl').'config/mail/icon/yeni.png" width="90" height="80"></th><th style="text-align:left"><h1 style="margin:0;color:#435062;font-size:24px;font-family:Montserrat,sans-serif;font-weight:600">Yeni Ödeme Bildirimi!</h1><p style="font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#afbcce;line-height:24px">Alt bölümde detayları verilen sipariş için ödeme bildirimi gönderildi.<br><br><a  style="text-decoration:none;font-weight: bold;padding: 7px 13px; background: #edf2f9;color:#435062;border-radius: 5px;" href="'.$ayar->getpage('odemeler',$odeme->o_code).'">Panele Git</a></p><br><br></th></tr>';
$icerik .= '<tr><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">Sipariş No</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left:2px solid #edf2f9;padding-left: 10px;">'.$siparis->sp_code.'</th></tr>';
$icerik .= '<tr style="background:#edf2f9"><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">Müşteri Adı</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #fff;padding-left: 10px;">'.$siparis->sp_musteri_adi.'</th></tr>';
$icerik .= '<tr><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">Sipariş</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left:2px solid #edf2f9;padding-left: 10px;">'.$siparis->sp_paket_adi.'</th></tr>';
$icerik .= '<tr style="background:#edf2f9"><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">Banka Seçimi</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #fff;padding-left: 10px;">'.$banka["item2"].'</th></tr>';
$icerik .= '<tr><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">Müşteri Açıklaması</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left:2px solid #edf2f9;padding-left: 10px;">'.$odeme->o_aciklama.'</th></tr>';
$icerik .= '<tr style="background:#edf2f9"><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">İşlem Adresi</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #fff;padding-left: 10px;">'.$siparis->islem_adres.'</th></tr>';
$icerik .= '<tr><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">Durum</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #edf2f9;padding-left: 10px;"><b>'.$item2.'</b></th></tr>';
$icerik .= '<tr style="background:#edf2f9"><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">Ödenmesi Gereken Tutar</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #fff;padding-left: 10px;"><b>'._p($odeme->o_tutar).'</b></th></tr>';
$icerik .='</table><br><a href="'.ns_filter('siteurl').'" style="text-decoration: none;color: #97a1af;padding:50px;"><img width="200" src="'.ns_filter('siteurl').ns_filter('sitelogo').'"></a><br><br><b>'.ns_filter('sitetitle').'</b><br><br><br></center></div>';
$mail->item = array(
    "to"=> $user->maillist,
    "Subject"=>"Yeni Ödeme Bildirimi!",
    "Content"=>$icerik);