<?
$user->action = $item2;
$uye = $user->select();
$icerik = '<div style="background: #edf2f9; height: 100%; text-align: center;"><br/><br/><center>';
$icerik .='<table style="max-width: 600px; padding: 10px;" border="0" width="100%" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr style="height: 179px;"><th style="height: 179px; width: 23.1667%;"><img src="'.ns_filter('siteurl').'config/mail/icon/success.png" width="80" height="80" /></th><th style="text-align: left; height: 179px; width: 69.8333%;"><br /><br /><h1 style="margin: 0px; color: #435062; font-size: 24px; font-family: Montserrat, sans-serif; font-weight: 600; text-align: center;">Şifre Yenileme İsteği!</h1><p style="font-family: Montserrat, sans-serif; font-weight: 400; font-size: 14px; color: #afbcce; line-height: 24px; text-align: center;">Panel giriş şifrenizi değiştirmek i&ccedil;in alt b&ouml;l&uuml;mde yer alan linke tıklayın ve şifrenizi sıfırlayın.</p><br /><br /></th></tr></tbody></table>';
$icerik .= '<table style="max-width: 600px; padding: 10px;" border="0" width="100%" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr style="background: #edf2f9; height: 28px;"><th style="text-align: left; padding-left: 10px; font-family: Montserrat, sans-serif; font-weight: 400; font-size: 14px; color: #8b929c; line-height: 28px; border-left: 2px solid #ffffff; height: 28px; width: 17%;"><div style="width: 100px;">Ad Soyad</div></th><th style="text-align: left; font-family: Montserrat, sans-serif; font-weight: 400; font-size: 14px; color: #435062; line-height: 28px; border-left: 2px solid #ffffff; padding-left: 10px; height: 28px; width: 75%;">'.$uye["k_adi"].'</th></tr><tr style="height: 28px;"><th style="text-align: left; padding-left: 10px; font-family: Montserrat, sans-serif; font-weight: 400; font-size: 14px; color: #8b929c; line-height: 28px; border-left: 2px solid #ffffff; height: 28px; width: 17%;"><div style="width: 100px;">Kullanıcı Adı</div></th><th style="text-align: left; font-family: Montserrat, sans-serif; font-weight: 400; font-size: 14px; color: #435062; line-height: 28px; border-left: 2px solid #edf2f9; padding-left: 10px; height: 28px; width: 75%;">'.$uye["k_kadi"].'</th></tr><tr style="background: #edf2f9; height: 28px;"><th style="text-align: left; padding-left: 10px; font-family: Montserrat, sans-serif; font-weight: 400; font-size: 14px; color: #8b929c; line-height: 28px; border-left: 2px solid #ffffff; height: 28px; width: 17%;"><div style="width: 100px;">Yenileme Linki</div></th><th style="text-align: left; font-family: Montserrat, sans-serif; font-weight: 400; font-size: 14px; color: #435062; line-height: 28px; border-left: 2px solid #ffffff; padding-left: 10px; height: 28px; width: 75%;">'.$ayar->getpage('sifre-yenile',$nsoft->passwordrefresh($uye)).'</th></tr></tbody></table>';
$icerik .= '<table style="max-width: 600px; padding: 10px;" border="0" width="100%" cellspacing="0" cellpadding="0" align="center" bgcolor="#ffffff"><tbody><tr><th style="text-align: center; width: 600px; height: 69px;"><br /><a style="text-decoration: none; font-weight: bold; padding: 7px 13px; background: #edf2f9; color: #435062; border-radius: 5px;" target="_blank" href="'.$ayar->getpage('sifre-yenile',$nsoft->passwordrefresh($uye)).'">ŞİRE YENİLEME LİNKİ</a> <br /><br /></th></tr></tbody></table>';
$icerik .='<br><a href="'.ns_filter('siteurl').'" style="text-decoration: none;color: #97a1af;padding:50px;"><img width="200" src="'.ns_filter('siteurl').ns_filter('sitelogo').'"></a><br><br><b>'.ns_filter('sitetitle').'</b><br><br><br></center></div>';
$mail->item = array(
    "to"=> array(array("mail"=> $uye["k_mail"],"name"=>$uye["k_adi"])),
    "Subject"=>"Şifre Yenileme İsteği!",
    "Content"=>$icerik);