<?php
$iletisim = isset($iletisim) ? $iletisim: new iletisim($db);
$iletisim->i_id = $item2;
$iletisim->select();
$icerik = '<div style="background: #edf2f9; height: 100%;"><br><br><center><table cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff" width="100%" style="max-width:600px;padding: 10px;" align="center"><tr><th width="120"><img src="'.ns_filter('siteurl').'config/mail/icon/mesaj.png" width="90" height="80"></th><th style="text-align:left"><h1 style="margin:0;color:#435062;font-size:24px;font-family:Montserrat,sans-serif;font-weight:600">'._e("İletişim isteğiniz yanıtlandı", true).'!</h1><p style="font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#afbcce;line-height:24px">'._e("Web sitemiz üzerinden oluşturduğunuz iletişim talebiniz cevaplandı", true).'.<br><br><a href="'.ns_filter('siteurl').'" style="text-decoration:none;font-weight: bold;padding: 7px 13px; background: #edf2f9;color:#435062;border-radius: 5px;">'._e("Siteye Git",true).'!</a></p><br><br></th></tr>';
$icerik .= '<tr><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">'._e("Ad Soyad",true).'</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left:2px solid #edf2f9;padding-left: 10px;">'.$iletisim->i_ad_soyad.'</th></tr>';
$icerik .= '<tr style="background:#edf2f9"><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">'._e("Mail Adresi",true).'</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #fff;padding-left: 10px;">'.$iletisim->i_mail.'</th></tr>';
$icerik .= '<tr><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">'._e("Telefon Numaranız",true).'</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left:2px solid #edf2f9;padding-left: 10px;">'.$iletisim->i_telefon.'</th></tr><tr style="background:#edf2f9"><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">'._e("Konu",true).'</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #fff;padding-left: 10px;">'.$iletisim->i_konu.'</th></tr>';
$icerik .= '<tr><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">'._e("Mesajınız",true).'</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #edf2f9;padding-left: 10px;"><b>'.$iletisim->i_mesaj.'</b></th></tr>';
$icerik .= '<tr style="background:#edf2f9"><th style="text-align:left;padding-left:16px;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color: #8b929c;line-height: 28px;border-left: 2px solid #fff; padding-left: 10px;"><div style="width:100px">'._e("Cevap",true).'</div></th><th style="text-align:left;font-family:Montserrat,sans-serif;font-weight:400;font-size:14px;color:#435062;line-height:28px;border-left: 2px solid #edf2f9;padding-left: 10px;"><b>'.$iletisim->i_cevap.'</b></th></tr>';
$icerik .='</table><br><a href="'.ns_filter('siteurl').'" style="text-decoration: none;color: #97a1af;padding:50px;"><img width="200" src="'.ns_filter('siteurl').ns_filter('sitelogo').'"></a><br><br><b>'.ns_filter('sitetitle').'</b><br><br><br></center></div>';
$mail->item = array(
    "to"=> array(array("mail"=>$iletisim->i_mail,"name"=>$iletisim->i_ad_soyad)),
    "Subject"=> _e("İletişim isteğiniz yanıtlandı", true),
    "Content"=>$icerik);

?>